version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: socialmedia
    ports:
      - 5432:5432
volumes:
  pgdata:
